<ul class="menu-list">
    <li title="Admin" class="active">
        <a href="#">
            <i class="fa fa-th-large"></i>
            <span>Admin</span>
            <b class="arrow fa fa-angle-left"></b>
        </a>
        <ul class="none sub-menu">
            <li>
            	<a href="#">
            		<i class="menu-icon fa fa-caret-right"></i>abc
            	</a>
            	<a href="#" class="open">
            		<i class="menu-icon fa fa-caret-right"></i>abc
            	</a>
            </li>
        </ul>
    </li>
</ul>

<script type="text/javascript">
	$('.menu-list>li>a').click(function(event) {
		/* Act on the event */
		$(this).parents('li').toggleClass('current');
		$(this).parent().find('ul').toggleClass('none');
		$(this).parent().toggleClass('active');
	});
</script>