<ul class="menu-list">
    <li title="Admin" class="<?php echo request()->controller() == 'account' ? 'current active' : ''?>">
        <a href="#">
            <i class="fa fa-th-large"></i>
            <span>Admin</span>
            <b class="arrow fa fa-angle-left"></b>
        </a>
        <ul class="<?php request()->controller() == 'account' ? '' : 'none'?> sub-menu">
            <li>
            	<a href="<?php echo url('account/mine')?>" class="<?php echo request()->action() == 'mine' ? 'open' : ''?>">
            		<i class="menu-icon fa fa-caret-right"></i>Mine
            	</a>
            	<a href="#">
            		<i class="menu-icon fa fa-caret-right"></i>abc
            	</a>
            </li>
        </ul>
    </li>
    <div class="sidebar-bottom clearfix"></div>
</ul>

<script type="text/javascript">
	$('.menu-list>li>a').click(function(event) {
		/* Act on the event */
		$(this).parents('li').toggleClass('current');
		$(this).parent().find('ul').toggleClass('none');
		$(this).parent().toggleClass('active');
	});
</script>