<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <meta http-equiv="content-language" content="zh-CN">
    <title>Forgot Password</title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="Shortcut Icon" type="image/ico" href="/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="__CSS__/common.css" />
    <link rel="stylesheet" type="text/css" href="__CSS__/admin-account.css" />
    <script type="text/javascript" src="__JS__/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="__JS__/core.popup.js"></script>
    <script type="text/javascript" src="__JS__/core.extend.js"></script>
    <script type="text/javascript" src="__JS__/core.ajaxauto.js"></script>
</head>
<body>
    <div class="container">
        <div class="login-container">
            <div class="logo-admin">Forgot Password</div>
            <form method="post" id="login-form" class="login-form">
                <div class="form-group">
                    <input class="form-control" type="text" name="login" value="<?php echo input('get.login')?>" placeholder="Username" required />
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="passwd" placeholder="Password" required />
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="d_passwd" placeholder="Duplicate Password" required />
                </div>
                <input class="form-control" type="hidden" name="redirect" value="<?php echo input('redirect');?>">
                <button type="submit" class="button primary">Submit</button>
            </form>
        </div>
    </div>
    <script>
        $('#login-form').submit(function() {
            $.check(this.passwd.value != this.d_passwd.value, '2次密码不一样') &&
            $(this).ajaxAuto({
                success: function (re) {
                    if (re.status == 'ok') {
                        // console.log(re);
                    }
                }
            });
            return false;
        });
    </script>
</body>
</html>