<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <meta http-equiv="content-language" content="zh-CN">
    <title><?php echo ucfirst($type)?></title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico" />
    <link rel="Shortcut Icon" type="image/ico" href="/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="__CSS__/common.css" />
    <link rel="stylesheet" type="text/css" href="__CSS__/admin-account.css" />
    <script type="text/javascript" src="__JS__/jquery-3.2.1.min.js"></script>
    <script type="text/javascript" src="__JS__/core.popup.js"></script>
    <script type="text/javascript" src="__JS__/core.ajaxauto.js"></script>
</head>
<body>
    <div class="container">
        <div class="login-container">
            <div class="logo-admin">Admin System</div>
            <form method="post" id="login-form" class="login-form">
                <div class="form-group">
                    <input class="form-control" type="text" name="login" placeholder="Username" required />
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="passwd" placeholder="Password" required />
                </div>
                <input class="form-control" type="hidden" name="redirect" value="<?php echo input('redirect');?>">
                <button type="submit" class="button primary"><?php echo ucfirst($type)?></button>
                <?php if ($type == 'login') : ?>
                    <a class="forget-pw" href="<?php echo url('admin/account/forgotPassword');?>">
                        <small>Forgot password?</small>
                    </a>
                <?php endif;?>
            </form>
        </div>
    </div>
    <script>
        $('#login-form').submit(function() {
            $(this).ajaxAuto({
                success: function (re) {
                    if (re.status == 'ok') {
                        // console.log(re);
                    }
                }
            });
            return false;
        });

        $('.forget-pw').click(function(event) {
            /* Act on the event */
            var login = $('input[name="login"]').val();
            if (login) {
                window.location.href = $(this).attr('href') + '?login=' + login;
                return false;
            }
        });
    </script>
</body>
</html>