<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
	<meta http-equiv="content-language" content="zh-CN">
	<title>123</title>
	<link rel="icon" type="image/x-icon" href="favicon.ico" />
    <link rel="Shortcut Icon" type="image/ico" href="favicon.ico" />
	<link rel="stylesheet" type="text/css" href="_CSS_/common.css" />
	<script type="text/javascript" src="_JS_/jquery-3.1.1.min.js"></script>
</head>
<body>
	<header>
		{include file='layout/includes/header'}
	</header>

	<div id="content">
		{__CONTENT__}
	</div>
	
	<footer>
		{include file='layout/includes/footer'}
	</footer>
</body>
</html>